# TimeRecorder Configuration File
# This file contains all configurable parameters for the TimeRecorder application

# Data processing settings
data_processing:
  use_boot_time: true  # Use system boot time as start time
  logging_enabled: false  # Set to True to log the results
  auto_squash: true  # Automatically squash duplicate entries
  add_missing_days: true  # Add missing days to logbook

# Time tracking settings
time_tracking:
  date: "01.08.2025"  # Date in DD.MM.YYYY format
  start_time: "07:00"  # Starting time in HH:MM format
  end_time: "17:15"  # Ending time in HH:MM format
  lunch_break_duration: 60  # Duration of the lunch break in minutes
  full_format: "%d.%m.%Y %H:%M:%S"  # Format string for parsing full datetime

# Logging settings
logging:
  log_path: "timereport_logbook.txt"  # Path to the log file (relative to current directory)
  log_level: "INFO"  # Logging level: DEBUG, INFO, WARNING, ERROR

# Work schedule settings
work_schedule:
  standard_work_hours: 8  # Standard work hours per day
  work_days: [0, 1, 2, 3, 4]  # Monday to Friday (0=Monday, 6=Sunday)
  timezone: "Europe/Berlin"  # Timezone for time calculations

# Holiday settings
holidays:
  country: "DE"  # Country code for holidays
  subdivision: "HE"  # State/province subdivision

# Display settings
display:
  calculate_weekly_hours: true  # Calculate weekly hours from log
  calculate_daily_overhours: true  # Calculate daily overhours from log
  show_tail: 4  # Show the last n lines of the logbook

# Visualization settings
visualization:
  plot: true  # Show the graphical output
  color_scheme: "ocean"  # Color scheme: ocean, forest, sunset, lavender, coral
  num_months: 13  # Number of months to show in daily hours plot
